version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - hass
  - gotify
  - desync
  - mbar
  - sonarjs
  - datetime
  - alexa
  - cbar
  - kbit
  - mbit
  - homeassistant
  - zeroconf
  - endregion
  - gbit
ignoreWords: []
import: []
