version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - alexa
  - cbar
  - comms
  - datetime
  - desync
  - endregion
  - gbit
  - gotify
  - hass
  - homeassistant
  - hvac
  - kbit
  - mbar
  - mbit
  - programminghorror
  - rgbw
  - rgbww
  - sonarjs
  - tvshow
  - utcnow
  - zeroconf
ignoreWords: []
import: []
